version: '2'
services:
  test:
    build: .
    image: cmsimagelambda
    command: test
    volumes:
      - ./lib:/app/lib
      - ./test:/app/test
      - ./package.json:/app/package.json
    env_file:
      - .env
