version: '2'
services:
  start:
    build: .
    image: cmsimagelambda
    command: start
    volumes:
      - .:/app
  test:
    image: cmsimagelambda
    command: test
    volumes:
      - ./bin:/app/bin
      - ./lib:/app/lib
      - ./test:/app/test
      - ./index.js:/app/index.js
